; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.31101.0 

	TITLE	C:\Users\Juni\Documents\Visual Studio 2013\Projects\ST2\ST2_day2\1_템플릿기본2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_main
PUBLIC	??$square@H@@YAHH@Z				; square<int>
; Function compile flags: /Odtp
; File c:\users\juni\documents\visual studio 2013\projects\st2\st2_day2\1_템플릿기본2.cpp
;	COMDAT ??$square@H@@YAHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
??$square@H@@YAHH@Z PROC				; square<int>, COMDAT

; 1    : template<typename T> T square(T a){

	push	ebp
	mov	ebp, esp

; 2    : 	return a*a;

	mov	eax, DWORD PTR _a$[ebp]
	imul	eax, DWORD PTR _a$[ebp]

; 3    : }

	pop	ebp
	ret	0
??$square@H@@YAHH@Z ENDP				; square<int>
_TEXT	ENDS
; Function compile flags: /Odtp
; File c:\users\juni\documents\visual studio 2013\projects\st2\st2_day2\1_템플릿기본2.cpp
_TEXT	SEGMENT
_s$ = -4						; size = 2
_main	PROC

; 4    : int main(){

	push	ebp
	mov	ebp, esp
	push	ecx

; 5    : 	short s = 3;

	mov	eax, 3
	mov	WORD PTR _s$[ebp], ax

; 6    : 
; 7    : 	square(3); //int 버전

	push	3
	call	??$square@H@@YAHH@Z			; square<int>
	add	esp, 4

; 8    : 	//square(s); //short 버전
; 9    : 	square<int>(s);

	movsx	ecx, WORD PTR _s$[ebp]
	push	ecx
	call	??$square@H@@YAHH@Z			; square<int>
	add	esp, 4

; 10   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
END
